### ISSUE TITLE
Can you make torchlevy available?

### ISSUE THREAD

**Issue by bewit** [jk4011/torchlevy_page#1]
Dear Dr. Jinhyeok Kim, 

Upon researching implementations of stable distributions, I've come across your [Pytorch feature request](https://github.com/pytorch/pytorch/issues/91300). I want to evaluate the quality of stable distributions in large mixture models and struggle with computing the density and distribution function of stable distributed variables while maintaining compatibility with the Pytorch library. Is there any chance that you make the respective repository public or that I can access the code in any other way? It would be a tremendous help to me.

Sincerely,
Bennet Wittelsbach

**Comment by jk4011** [comment]
Hello @bewit , 
The above feature request failed because I can't remove the dependency on another package. 
And I am not authorized to open the torchlevy code, because I am not a member of the lab anymore.
I will ask another researcher in the lab. 

@eunbi1 은비님, 혹시 torchlevy를 public으로 만들 수 있나요?

**Comment by eunbi1** [comment]
Public으로 바꿨습니다!

2024년 5월 9일 (목) 오전 11:41, Jinhyeok Kim ***@***.***>님이 작성:

**Comment by bewit** [comment]
Thank you very much!

**Comment by bewit** [comment]
Sorry to bother you once more, @eunbi1, but I'm not sure if we talked about the same repository. I meant to ask to make https://github.com/UNIST-LIM-Lab/torchlevy public, but I still have no access.

**Comment by jk4011** [comment]
@bewit  I checked it, it is public now.
